// Script de diagnóstico para el problema del costo por par
console.log('🔍 DIAGNÓSTICO DEL PROBLEMA DEL COSTO POR PAR');
console.log('=============================================');
console.log('');
console.log('🎯 PROBLEMA IDENTIFICADO:');
console.log('=========================');
console.log('');
console.log('❌ El "Costo por Par" aparece como "$ 0,00"');
console.log('❌ Los materiales del BOM no están encontrando sus costos');
console.log('❌ Posibles causas:');
console.log('   • Datos no cargados correctamente');
console.log('   • IDs de materiales no coinciden');
console.log('   • Costos no disponibles en inventario');
console.log('');
console.log('🧪 VERIFICACIÓN PASO A PASO:');
console.log('==============================');
console.log('');
console.log('1. 📊 Verificar datos en localStorage:');
console.log('   • Abrir DevTools (F12) → Application → Local Storage');
console.log('   • Buscar "sismac_productModels"');
console.log('   • Buscar "sismac_inventoryData"');
console.log('');
console.log('2. 🔍 Verificar IDs coincidentes:');
console.log('   • Product Model BOM IDs:');
console.log('     - PUNTERA_9, OJILLERO_10, REMATE_12, etc.');
console.log('   • Inventory Data IDs:');
console.log('     - PUNTERA_9, OJILLERO_10, REMATE_12, etc.');
console.log('');
console.log('3. 💰 Verificar costos disponibles:');
console.log('   • Cada material debe tener "unitCost"');
console.log('   • Verificar que los costos no sean 0 o null');
console.log('');
console.log('🔧 SOLUCIONES POSIBLES:');
console.log('=======================');
console.log('');
console.log('✅ Solución 1: Verificar datos en localStorage');
console.log('   - Limpiar localStorage completamente');
console.log('   - Recargar la página para forzar carga de datos');
console.log('');
console.log('✅ Solución 2: Verificar formato de datos');
console.log('   - Asegurar que materialSku coincida exactamente');
console.log('   - Verificar que unitCost tenga valores numéricos');
console.log('');
console.log('✅ Solución 3: Agregar logging para debugging');
console.log('   - Abrir consola del navegador');
console.log('   - Buscar mensajes de carga de datos');
console.log('');
console.log('🧪 INSTRUCCIONES PARA DEBUGGING:');
console.log('=================================');
console.log('');
console.log('1. 🌐 Abrir: http://localhost:3000');
console.log('2. 🔐 Iniciar sesión: plan / sismac123');
console.log('3. 📋 Ir a "Planificación" → "Crear Orden"');
console.log('4. 🔧 Abrir DevTools (F12) → Console');
console.log('5. 🔄 Recargar página (Ctrl+R)');
console.log('');
console.log('6. 📊 Verificar en Console:');
console.log('   ✅ Buscar: "🔧 Verificando datos existentes"');
console.log('   ✅ Buscar: "🔧 No hay datos completos, cargando datos reales"');
console.log('   ✅ Buscar: "✅ Datos reales del modelo VAZZA 13501 BLANCO cargados"');
console.log('');
console.log('7. 🗂️ Verificar en Application → Local Storage:');
console.log('   ✅ sismac_productModels debe tener datos');
console.log('   ✅ sismac_inventoryData debe tener datos');
console.log('');
console.log('8. 🎯 Probar solución:');
console.log('   ✅ Si no hay datos, limpiar localStorage');
console.log('   ✅ Recargar página');
console.log('   ✅ Verificar que aparezcan los datos');
console.log('');
console.log('🚀 SOLUCIÓN RECOMENDADA:');
console.log('========================');
console.log('');
console.log('✅ PASO 1: Limpiar localStorage completamente');
console.log('   - DevTools → Application → Local Storage');
console.log('   - Eliminar todas las entradas de "sismac_"');
console.log('');
console.log('✅ PASO 2: Recargar página');
console.log('   - Ctrl+R o F5');
console.log('   - Ver consola para confirmar carga de datos');
console.log('');
console.log('✅ PASO 3: Verificar resultado');
console.log('   - Ir a "Planificación" → "Crear Orden"');
console.log('   - Verificar que "Costo por Par" muestre valor correcto');
console.log('');
console.log('🎯 CAUSA PROBABLE:');
console.log('===================');
console.log('');
console.log('❌ Los datos no se están cargando correctamente al iniciar la aplicación');
console.log('❌ localStorage podría tener datos corruptos o incompletos');
console.log('❌ Los IDs de materiales podrían no coincidir exactamente');
console.log('');
console.log('✅ La solución es limpiar localStorage y recargar la página');
console.log('');
console.log('💡 Si el problema persiste, revisar que:');
console.log('   • Los IDs en el BOM coincidan exactamente con el inventario');
console.log('   • Los costos unitarios estén definidos correctamente');
console.log('   • No haya errores de JavaScript en consola');
