// Script de emergencia para solucionar el problema del costo por par
console.log('🚨 SOLUCIÓN DE EMERGENCIA: COSTO POR PAR = $0,00');
console.log('==================================================');
console.log('');
console.log('🎯 PROBLEMA DETECTADO:');
console.log('======================');
console.log('');
console.log('❌ localStorage tiene datos incorrectos (datos de prueba)');
console.log('❌ Los datos del modelo VAZZA no se están cargando');
console.log('❌ "Costo por Par" aparece como $0,00');
console.log('');
console.log('🔧 SOLUCIÓN INMEDIATA:');
console.log('======================');
console.log('');
console.log('✅ Opción 1: Limpiar localStorage y recargar');
console.log('   1. Abrir DevTools (F12) → Application → Local Storage');
console.log('   2. Eliminar todas las entradas que empiecen con "sismac_"');
console.log('   3. Recargar página (F5 o Ctrl+R)');
console.log('');
console.log('✅ Opción 2: Usar función de emergencia desde consola');
console.log('   1. Abrir DevTools (F12) → Console');
console.log('   2. Ejecutar: clearAndReloadData()');
console.log('   3. La página se recargará automáticamente');
console.log('');
console.log('✅ Opción 3: Verificar datos actuales');
console.log('   1. Abrir DevTools (F12) → Application → Local Storage');
console.log('   2. Buscar "sismac_productModels"');
console.log('   3. Verificar que contenga el modelo VAZZA');
console.log('');
console.log('🧪 INSTRUCCIONES DETALLADAS:');
console.log('=============================');
console.log('');
console.log('PASO 1: Abrir DevTools');
console.log('   • Presiona F12 o haz clic derecho → "Inspeccionar"');
console.log('   • Ve a la pestaña "Console"');
console.log('');
console.log('PASO 2: Ejecutar función de emergencia');
console.log('   • Escribe en la consola: clearAndReloadData()');
console.log('   • Presiona Enter');
console.log('   • La página se recargará automáticamente');
console.log('');
console.log('PASO 3: Verificar resultado');
console.log('   • Ve a "Planificación" → "Crear Orden"');
console.log('   • Verifica que "Costo por Par" muestre $372.32');
console.log('   • Verifica que "Materiales en BOM" muestre 20');
console.log('');
console.log('🎯 RESULTADO ESPERADO:');
console.log('======================');
console.log('');
console.log('✅ "Costo por Par": $372.32 (en lugar de $0,00)');
console.log('✅ "Materiales en BOM": 20 (en lugar de 3)');
console.log('✅ "ID del Modelo": MOD-VAZZA-13501-BLANCO');
console.log('✅ Datos del modelo VAZZA cargados correctamente');
console.log('');
console.log('🔍 VERIFICACIÓN EN CONSOLA:');
console.log('=============================');
console.log('');
console.log('Después de ejecutar clearAndReloadData(), busca en la consola:');
console.log('✅ "🔧 Cargando datos reales del modelo VAZZA 13501 BLANCO"');
console.log('✅ "✅ Datos reales del modelo VAZZA 13501 BLANCO cargados automáticamente"');
console.log('✅ "📋 Modelos disponibles: 1 con 20 materiales"');
console.log('✅ "📦 Materiales en inventario: 20"');
console.log('');
console.log('💡 COMANDO DE EMERGENCIA:');
console.log('==========================');
console.log('');
console.log('Si prefieres ejecutar directamente en la consola del navegador:');
console.log('');
console.log('clearAndReloadData()');
console.log('');
console.log('O manualmente:');
console.log('localStorage.clear(); location.reload();');
console.log('');
console.log('🚀 ESTE ES EL COMANDO QUE NECESITAS EJECUTAR AHORA:');
console.log('===================================================');
console.log('');
console.log('En la consola del navegador (F12 → Console), ejecuta:');
console.log('clearAndReloadData()');
console.log('');
console.log('¡Esto solucionará el problema inmediatamente!');
